In [1]:
import numpy as np

In [2]:
# 0으로 채운 길이 10의 정수 배열 
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.array([1,2,3,4],dtype = float)    #'float32' 처럼 특정한 메모리를 지정하고 싶을 경우 '' 사용 

array([ 1.,  2.,  3.,  4.])

In [5]:
# 1로 채운 3*5 부동 소수점 배열 만들기
np.ones((3,5),dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [7]:
# 3.14로 채운 3*5 배열 만들기 
# np.full(shape, 값 )
np.full((3,5),3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [8]:
# 선형 수열로 채운 배열 만들기
# 0으로 시작해 2씩 더해 20까지 채움 
# (내장 함수인 range() 와 유사함)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.arange(0,20,2, dtype= float)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.])

In [10]:
# 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [12]:
# 균등하게 분포된 3*3 배열 만들기
# 0과 1 사이의 난수로 채움 
# np.random 서브 패키지 
np.random.random((3,3))

array([[ 0.02608818,  0.77022814,  0.46303571],
       [ 0.83133437,  0.24766186,  0.40387946],
       [ 0.41593432,  0.79954748,  0.0414173 ]])

In [13]:
# 정규 분포 (평균 =0, 표준 편차 =1)의 난수로 채운 3*3 배열 만들기
# np.random.normal(E(x),sd(x),shape)
np.random.normal(0,1,(3,3))

array([[ 0.62136325, -2.80186118, -0.2311933 ],
       [ 1.29292242, -0.0849179 ,  0.39163261],
       [-0.0877235 ,  0.06211705,  0.77748651]])

In [14]:
# [0,10] 구간의 임의의 정수로 채운 3*3 배열 만들기
np.random.randint(0,10,(3,3))

array([[1, 7, 4],
       [4, 8, 5],
       [2, 6, 9]])

In [15]:
#3*3 단위행렬
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [16]:
# 세 개 의 정수를 가지는 초기회되자 않은 배열
# 값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움
# 메모리를 잡아놓고 나중에 값을 할당하기 위한 과정 
np.empty(3)

array([ 1.,  1.,  1.])