In [1]:
import numpy as np

In [3]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)  # 모든 ufunc 함수에 out 인수를 활용하여 출력 지정 가능 
print(y)

[  0.  10.  20.  30.  40.]


In [5]:
y =np.zeros(10)
np.power(2,x,out=y[::2])   #지정한 배열의 요소에 하나씩 건너뛰면서 기록 가능 
print(y)

[  1.   0.   2.   0.   4.   0.   8.   0.  16.   0.]


In [7]:
x= np.arange(1,6)
np.add.reduce(x)   # 집계연산 가능 : reduce 

15

In [8]:
np.multiply.reduce(x)

120

In [10]:
np.multiply.accumulate(x)  # 중간 연산 과정을 기록 하는 함수 : accumulate 

array([  1,   2,   6,  24, 120])

In [12]:
x= np.arange(1,6)
np.multiply.outer(x,x)     # outer : 모든 쌍에 대한 출력값 

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [13]:
np.add.outer(x,x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])