In [1]:
import numpy as np

In [2]:
L= np.random.random(100)
sum(L)

47.725119569858698

In [3]:
np.sum(L)

47.725119569858684

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 103 ms per loop
1000 loops, best of 3: 557 µs per loop


In [6]:
M=np.random.random((3,4))

In [7]:
print(M)

[[ 0.58893315  0.56093438  0.14832038  0.50059958]
 [ 0.31305268  0.36815245  0.61813148  0.7190608 ]
 [ 0.69337856  0.40569869  0.71325752  0.53846514]]


In [8]:
M.sum()

6.1679848079172279

In [9]:
M.min(axis=0)  # axis =0 각 열마다 

array([ 0.31305268,  0.36815245,  0.14832038,  0.50059958])

In [10]:
M.max(axis=1)  # axis= 1각 행마다 

array([ 0.58893315,  0.7190608 ,  0.71325752])