In [1]:
!pwd

/Users/jihye/PDSH


In [2]:
import numpy as np

In [3]:
grid = np.arange(1,10).reshape((3,3))

In [5]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#reshape : 초기 배열 의 규모가 형상이 변경된 배열의 규모와 일치해야만 사용 가능
x = np.array([1,2,3])
# reshape 을 이용한 행 벡터 
x.reshape((1,3))

array([[1, 2, 3]])

In [9]:
#newaxis 를 이용한 행 벡터 
x[np.newaxis,:]

array([[1, 2, 3]])

In [10]:
# newaxis 를 이용한 열 벡터 
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [12]:
#np.concatenate : 두 배열을 연결 , 결합 
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [13]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [15]:
grid= np.array([[1,2,3],
                [4,5,6]])

In [16]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# 첫 번째 축을 따라 연결
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [21]:
# 두 번째 축을 따라 연결 (0부터 시작하는 인덱스 방식)
np.concatenate([grid,grid],axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [22]:
x= np.array([1,2,3])
grid=np.array([[9,8,7],
               [6,5,4]])
# 배열을 수직으로 쌓음 
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [23]:
# 배열을 수평으로 쌓음
y=np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [24]:
# np.dstack : 세번쨰 축에 따라 배열을 쌓는 것 
a = np.array([[[1],[1]],
              [[2],[2]],
              [[3],[3]]])
b = np.array([[[4],[4]],
              [[5],[5]],
              [[6],[6]]])

np.dstack([a,b])

array([[[1, 4],
        [1, 4]],

       [[2, 5],
        [2, 5]],

       [[3, 6],
        [3, 6]]])

In [25]:
# np.split :  분할지점을 설정하고 그 값 앞에서 자름
x =[1,2,3,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99  3] [2 1]


In [26]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
#np.vsplit : 행 단위로  자르기 
upper, lower = np.vsplit(grid,[2]) 
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [28]:
upper,mid, lower = np.vsplit(grid,[1,3]) 
print(upper)
print(mid)
print(lower)

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [29]:
#np.hsplit : 열 단위로 자르기
left, right= np.hsplit(grid,[2]) 
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
