In [1]:
import numpy as np

In [2]:
L=list(range(10))

In [3]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(L[0])

int

In [6]:
L2 = [str(c) for c in L]

In [7]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
type(L2[0])

str

In [10]:
L3=[True,"2",3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

In [11]:
[type(item) for item in L3]

[bool, str, float, int]

In [14]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.array([1,4,5,6,3])

array([1, 4, 5, 6, 3])

In [17]:
np.array([3.14,4,5,3,2])
# 타입이 일치하지 않으면 가능한 경우 상위 타입을 취함 

array([ 3.14,  4.  ,  5.  ,  3.  ,  2.  ])

In [18]:
np.array([1,2,3,4],dtype = 'float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [22]:
# 리스트를 중첩하면 다차원 배열이 됨 
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [23]:
sh = np.array([range(i, i+3) for i in [2,4,6]])
sh.shape

(3, 3)