In [1]:
import numpy as np

In [2]:
np.random.seed(0)  # 재현 가능성을 위한 시드 값 

x1 = np.random.randint(10, size=6 ) # 1차원 배열 
x2 = np.random.randint(10, size=(3,4)) # 2차원 배열 
x3 = np.random.randint(10, size=(3,4,5)) # 3차원 배열 

In [3]:
print("x3 ndim : ", x3.ndim)        # 3차원 
print("x3 shape : ", x3.shape)      # 형태
print("x3 size : ", x3.size)        # 가지는 값의 개수 3*4*5 = 60  

x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60


In [4]:
print("dtype : ",x3.dtype)

dtype :  int64


In [5]:
print("itemsize : " , x3.itemsize, "bytes")
print("nbytes : " , x3.nbytes, "bytes") 

itemsize :  8 bytes
nbytes :  480 bytes


In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0]

5

In [8]:
x1[4]

7

In [9]:
x1[-1]

9

In [10]:
x1[-2]

7

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
x2[0,0]

3

In [13]:
x2[2,0]

1

In [14]:
x2[2,-1]

7

In [16]:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [17]:
x1[0]=3.14159
# 정수배열에 부동 소수점 값 추가하려 할때 자동 소수점 아래 잘림 

In [18]:
x1

array([3, 0, 3, 3, 7, 9])

In [19]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[:5]   # 첫번째 5개 요소

array([0, 1, 2, 3, 4])

In [21]:
x[5:]   # 인덱스 5 다음 모든 요소들 

array([5, 6, 7, 8, 9])

In [22]:
x[4:7]  # 중간 하위 배열 

array([4, 5, 6])

In [23]:
x[::2]  # 하나 걸러 하나씩 구성 

array([0, 2, 4, 6, 8])

In [24]:
x[1::2] #1부터 시작해 하나 걸러 하나씩 

array([1, 3, 5, 7, 9])

In [26]:
x[::-1]  # 거꾸로 나열 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
x[5::-2] #인덱스 5부터 거꾸로 

array([5, 3, 1])

In [28]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [29]:
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [30]:
x2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [31]:
x2[::-1,::-1] # 역으로 변환 

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [33]:
print(x2[:,0])  #첫번째 열

[12  7  1]


In [34]:
print(x2[0,:]) # 첫번째 행 

[12  5  2  4]


In [35]:
print(x2[0]) #x2[0,:] 과 동일, 첫번째 행 

[12  5  2  4]


In [36]:
x2_sub= x2[:2,:2]  # array 는 copy가 아닌 view로 하위 배열을 수정할 경우 원래 배열 역시 변환 
print(x2_sub)

[[12  5]
 [ 7  6]]


In [37]:
x2_sub[0,0]=99
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [38]:
x2_sub_copy=x2[:2,:2].copy()  # 배열을 완전히 복사하고자 할 경우 copy() 함수 사용 
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [39]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])